/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package fr.vendredi.web.domain.more;

import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.model.LazyDataModel;
import fr.vendredi.domain.more.MoreTypesDemo;
import fr.vendredi.repository.more.MoreTypesDemoRepository;
import fr.vendredi.web.converter.more.MoreTypesDemoJsfConverter;
import fr.vendredi.web.domain.support.GenericLazyDataModel;
import fr.vendredi.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link MoreTypesDemo}
 */
@Named
@ConversationContextScoped
public class MoreTypesDemoLazyDataModel extends GenericLazyDataModel<MoreTypesDemo, Integer, MoreTypesDemoSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public MoreTypesDemoLazyDataModel(MoreTypesDemoRepository moreTypesDemoRepository, MoreTypesDemoJsfConverter moreTypesDemoConverter,
            MoreTypesDemoController moreTypesDemoController, MoreTypesDemoSearchForm moreTypesDemoSearchForm) {
        super(moreTypesDemoRepository, moreTypesDemoConverter, moreTypesDemoController, moreTypesDemoSearchForm);
    }
}