/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package fr.vendredi.web.domain.more;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import fr.vendredi.domain.more.MoreTypesDemo;
import fr.vendredi.repository.more.MoreTypesDemoRepository;
import fr.vendredi.web.domain.support.GenericController;
import fr.vendredi.web.permission.more.MoreTypesDemoPermission;

/**
 * Stateless controller for {@link MoreTypesDemo} conversation start. 
 */
@Named
@Singleton
public class MoreTypesDemoController extends GenericController<MoreTypesDemo, Integer> {
    public static final String MORETYPESDEMO_EDIT_URI = "/domain/more/moreTypesDemoEdit.faces";
    public static final String MORETYPESDEMO_SELECT_URI = "/domain/more/moreTypesDemoSelect.faces";

    @Inject
    public MoreTypesDemoController(MoreTypesDemoRepository moreTypesDemoRepository, MoreTypesDemoPermission moreTypesDemoPermission) {
        super(moreTypesDemoRepository, moreTypesDemoPermission, MORETYPESDEMO_SELECT_URI, MORETYPESDEMO_EDIT_URI);
    }
}