/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package fr.vendredi.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import fr.vendredi.dao.support.SearchParameters;
import fr.vendredi.domain.Account;
import fr.vendredi.domain.Account_;
import fr.vendredi.repository.AccountRepository;
import fr.vendredi.web.domain.support.GenericController;
import fr.vendredi.web.permission.AccountPermission;

/**
 * Stateless controller for {@link Account} conversation start. 
 */
@Named
@Singleton
public class AccountController extends GenericController<Account, String> {
    public static final String ACCOUNT_EDIT_URI = "/domain/accountEdit.faces";
    public static final String ACCOUNT_SELECT_URI = "/domain/accountSelect.faces";

    @Inject
    public AccountController(AccountRepository accountRepository, AccountPermission accountPermission) {
        super(accountRepository, accountPermission, ACCOUNT_SELECT_URI, ACCOUNT_EDIT_URI);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        return searchParameters.orderBy(Account_.username);
    }
}