/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package fr.vendredi.web.domain;

import static fr.vendredi.dao.support.EntitySelector.newEntitySelector;
import static fr.vendredi.dao.support.PropertySelector.newPropertySelector;
import static fr.vendredi.dao.support.Ranges.RangeDate.newRangeDate;
import javax.inject.Named;
import fr.vendredi.dao.support.EntitySelector;
import fr.vendredi.dao.support.PropertySelector;
import fr.vendredi.dao.support.Ranges.RangeDate;
import fr.vendredi.dao.support.SearchParameters;
import fr.vendredi.domain.Account;
import fr.vendredi.domain.Account_;
import fr.vendredi.domain.Address;
import fr.vendredi.domain.Civility;
import fr.vendredi.web.domain.support.GenericSearchForm;
import fr.vendredi.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link Account}.
 * It exposes a {@link Account} instance so it can be used in search by Example query.
 */
@Named
@ConversationContextScoped
public class AccountSearchForm extends GenericSearchForm<Account, String, AccountSearchForm> {
    private static final long serialVersionUID = 1L;

    protected Account account = new Account();
    protected RangeDate<Account> birthDateRange = newRangeDate(Account_.birthDate);
    protected PropertySelector<Account, String> usernameSelector = newPropertySelector(Account_.username);
    protected PropertySelector<Account, String> passwordSelector = newPropertySelector(Account_.password);
    protected PropertySelector<Account, String> emailSelector = newPropertySelector(Account_.email);
    protected PropertySelector<Account, Boolean> isEnabledSelector = newPropertySelector(Account_.isEnabled);
    protected PropertySelector<Account, Civility> civilitySelector = newPropertySelector(Account_.civility);
    protected PropertySelector<Account, String> firstNameSelector = newPropertySelector(Account_.firstName);
    protected PropertySelector<Account, String> lastNameSelector = newPropertySelector(Account_.lastName);
    protected PropertySelector<Account, String> descriptionSelector = newPropertySelector(Account_.description);
    protected EntitySelector<Account, Address, Integer> homeAddressSelector = newEntitySelector(Account_.homeAddress);

    public Account getAccount() {
        return account;
    }

    @Override
    protected Account getEntity() {
        return getAccount();
    }

    @Override
    public AccountSearchForm newInstance() {
        return new AccountSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        return new SearchParameters() //
                .anywhere() //
                .leftJoin(Account_.homeAddress) //
                .term(term) //
                .range(birthDateRange) //
                .property(usernameSelector) //
                .property(passwordSelector) //
                .property(emailSelector) //
                .property(isEnabledSelector) //
                .property(civilitySelector) //
                .property(firstNameSelector) //
                .property(lastNameSelector) //
                .property(descriptionSelector) //
                .entity(homeAddressSelector) //
        ;
    }

    @Override
    public void resetWithOther(AccountSearchForm other) {
        this.account = other.getAccount();
        this.term = other.getTerm();
        this.birthDateRange = other.getBirthDateRange();
        this.usernameSelector = other.getUsernameSelector();
        this.passwordSelector = other.getPasswordSelector();
        this.emailSelector = other.getEmailSelector();
        this.isEnabledSelector = other.getIsEnabledSelector();
        this.civilitySelector = other.getCivilitySelector();
        this.firstNameSelector = other.getFirstNameSelector();
        this.lastNameSelector = other.getLastNameSelector();
        this.descriptionSelector = other.getDescriptionSelector();
        this.homeAddressSelector = other.getHomeAddressSelector();
    }

    // Ranges
    public RangeDate<Account> getBirthDateRange() {
        return birthDateRange;
    }

    // Property selectors
    public PropertySelector<Account, String> getUsernameSelector() {
        return usernameSelector;
    }

    public PropertySelector<Account, String> getPasswordSelector() {
        return passwordSelector;
    }

    public PropertySelector<Account, String> getEmailSelector() {
        return emailSelector;
    }

    public PropertySelector<Account, Boolean> getIsEnabledSelector() {
        return isEnabledSelector;
    }

    public PropertySelector<Account, Civility> getCivilitySelector() {
        return civilitySelector;
    }

    public PropertySelector<Account, String> getFirstNameSelector() {
        return firstNameSelector;
    }

    public PropertySelector<Account, String> getLastNameSelector() {
        return lastNameSelector;
    }

    public PropertySelector<Account, String> getDescriptionSelector() {
        return descriptionSelector;
    }

    // Relation selectors
    public EntitySelector<Account, Address, Integer> getHomeAddressSelector() {
        return homeAddressSelector;
    }
}
