/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package fr.vendredi.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.model.LazyDataModel;
import fr.vendredi.domain.Account;
import fr.vendredi.repository.AccountRepository;
import fr.vendredi.web.converter.AccountJsfConverter;
import fr.vendredi.web.domain.support.GenericLazyDataModel;
import fr.vendredi.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Account}
 */
@Named
public class AccountLazyDataModel extends GenericLazyDataModel<Account, String, AccountSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public AccountLazyDataModel(AccountRepository accountRepository, AccountJsfConverter accountConverter, AccountController accountController,
            AccountSearchForm accountSearchForm) {
        super(accountRepository, accountConverter, accountController, accountSearchForm);
    }
}