/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package fr.vendredi.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import fr.vendredi.domain.Address;
import fr.vendredi.repository.AddressRepository;
import fr.vendredi.web.domain.support.GenericController;
import fr.vendredi.web.permission.AddressPermission;

/**
 * Stateless controller for {@link Address} conversation start. 
 */
@Named
@Singleton
public class AddressController extends GenericController<Address, Integer> {
    public static final String ADDRESS_EDIT_URI = "/domain/addressEdit.faces";
    public static final String ADDRESS_SELECT_URI = "/domain/addressSelect.faces";

    @Inject
    public AddressController(AddressRepository addressRepository, AddressPermission addressPermission) {
        super(addressRepository, addressPermission, ADDRESS_SELECT_URI, ADDRESS_EDIT_URI);
    }
}