/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package fr.vendredi.web.domain;

import static fr.vendredi.dao.support.EntitySelector.newEntitySelector;
import javax.inject.Named;
import fr.vendredi.dao.support.EntitySelector;
import fr.vendredi.dao.support.SearchParameters;
import fr.vendredi.domain.Account;
import fr.vendredi.domain.Document;
import fr.vendredi.domain.Document_;
import fr.vendredi.web.domain.support.GenericSearchForm;
import fr.vendredi.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link Document}.
 * It exposes a {@link Document} instance so it can be used in search by Example query.
 */
@Named
@ConversationContextScoped
public class DocumentSearchForm extends GenericSearchForm<Document, String, DocumentSearchForm> {
    private static final long serialVersionUID = 1L;

    protected Document document = new Document();
    protected EntitySelector<Document, Account, String> ownerSelector = newEntitySelector(Document_.owner);

    public Document getDocument() {
        return document;
    }

    @Override
    protected Document getEntity() {
        return getDocument();
    }

    @Override
    public DocumentSearchForm newInstance() {
        return new DocumentSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        return new SearchParameters() //
                .anywhere() //
                .leftJoin(Document_.owner) //
                .term(term) //
                .entity(ownerSelector) //
        ;
    }

    @Override
    public void resetWithOther(DocumentSearchForm other) {
        this.document = other.getDocument();
        this.term = other.getTerm();
        this.ownerSelector = other.getOwnerSelector();
    }

    // Relation selectors
    public EntitySelector<Document, Account, String> getOwnerSelector() {
        return ownerSelector;
    }
}
