/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package fr.vendredi.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import fr.vendredi.domain.Document;
import fr.vendredi.repository.DocumentRepository;
import fr.vendredi.web.domain.support.GenericController;
import fr.vendredi.web.permission.DocumentPermission;

/**
 * Stateless controller for {@link Document} conversation start. 
 */
@Named
@Singleton
public class DocumentController extends GenericController<Document, String> {
    public static final String DOCUMENT_EDIT_URI = "/domain/documentEdit.faces";
    public static final String DOCUMENT_SELECT_URI = "/domain/documentSelect.faces";

    @Inject
    public DocumentController(DocumentRepository documentRepository, DocumentPermission documentPermission) {
        super(documentRepository, documentPermission, DOCUMENT_SELECT_URI, DOCUMENT_EDIT_URI);
    }

    public DocumentFileUpload getDocumentFileUpload(Document document) {
        return new DocumentFileUpload(document);
    }
}