/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package fr.vendredi.web.domain;

import static fr.vendredi.dao.support.PropertySelector.newPropertySelector;
import javax.inject.Named;
import fr.vendredi.dao.support.PropertySelector;
import fr.vendredi.dao.support.SearchParameters;
import fr.vendredi.domain.Legacy;
import fr.vendredi.domain.LegacyPk;
import fr.vendredi.domain.Legacy_;
import fr.vendredi.web.domain.support.GenericSearchForm;
import fr.vendredi.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link Legacy}.
 * It exposes a {@link Legacy} instance so it can be used in search by Example query.
 */
@Named
@ConversationContextScoped
public class LegacySearchForm extends GenericSearchForm<Legacy, LegacyPk, LegacySearchForm> {
    private static final long serialVersionUID = 1L;

    protected Legacy legacy = new Legacy();
    protected PropertySelector<Legacy, String> extraInfoSelector = newPropertySelector(Legacy_.extraInfo);

    public Legacy getLegacy() {
        return legacy;
    }

    @Override
    protected Legacy getEntity() {
        return getLegacy();
    }

    @Override
    public LegacySearchForm newInstance() {
        return new LegacySearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        return new SearchParameters() //
                .anywhere() //
                .property(extraInfoSelector) //
        ;
    }

    @Override
    public void resetWithOther(LegacySearchForm other) {
        this.legacy = other.getLegacy();
        this.extraInfoSelector = other.getExtraInfoSelector();
    }

    // Property selectors
    public PropertySelector<Legacy, String> getExtraInfoSelector() {
        return extraInfoSelector;
    }
}
