/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package fr.vendredi.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.model.LazyDataModel;
import fr.vendredi.domain.Legacy;
import fr.vendredi.domain.LegacyPk;
import fr.vendredi.repository.LegacyRepository;
import fr.vendredi.web.converter.LegacyJsfConverter;
import fr.vendredi.web.domain.support.GenericLazyDataModel;
import fr.vendredi.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Legacy}
 */
@Named
@ConversationContextScoped
public class LegacyLazyDataModel extends GenericLazyDataModel<Legacy, LegacyPk, LegacySearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public LegacyLazyDataModel(LegacyRepository legacyRepository, LegacyJsfConverter legacyConverter, LegacyController legacyController,
            LegacySearchForm legacySearchForm) {
        super(legacyRepository, legacyConverter, legacyController, legacySearchForm);
    }
}