/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package fr.vendredi.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.model.LazyDataModel;
import fr.vendredi.domain.SavedSearch;
import fr.vendredi.repository.SavedSearchRepository;
import fr.vendredi.web.converter.SavedSearchJsfConverter;
import fr.vendredi.web.domain.support.GenericLazyDataModel;
import fr.vendredi.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link SavedSearch}
 */
@Named
@ConversationContextScoped
public class SavedSearchLazyDataModel extends GenericLazyDataModel<SavedSearch, Integer, SavedSearchSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public SavedSearchLazyDataModel(SavedSearchRepository savedSearchRepository, SavedSearchJsfConverter savedSearchConverter,
            SavedSearchController savedSearchController, SavedSearchSearchForm savedSearchSearchForm) {
        super(savedSearchRepository, savedSearchConverter, savedSearchController, savedSearchSearchForm);
    }
}