/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package fr.vendredi.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;
import fr.vendredi.domain.Account;
import fr.vendredi.domain.SavedSearch;
import fr.vendredi.repository.SavedSearchRepository;
import fr.vendredi.web.domain.AccountController;
import fr.vendredi.web.domain.SavedSearchController;
import fr.vendredi.web.domain.SavedSearchGraphLoader;
import fr.vendredi.web.domain.support.GenericEditForm;
import fr.vendredi.web.domain.support.GenericToOneAssociation;
import fr.vendredi.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link SavedSearch}.
 */
@Named
@ConversationContextScoped
public class SavedSearchEditForm extends GenericEditForm<SavedSearch, Integer> {
    @Inject
    protected SavedSearchController savedSearchController;
    @Inject
    protected AccountController accountController;
    protected GenericToOneAssociation<Account, String> account;

    @Inject
    public SavedSearchEditForm(SavedSearchRepository savedSearchRepository, SavedSearchGraphLoader savedSearchGraphLoader) {
        super(savedSearchRepository, savedSearchGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public SavedSearch getSavedSearch() {
        return getEntity();
    }

    public String print() {
        return savedSearchController.print(getSavedSearch());
    }

    @PostConstruct
    void setupAccountsActions() {
        account = new GenericToOneAssociation<Account, String>("savedSearch_account", accountController) {
            @Override
            protected Account get() {
                return getSavedSearch().getAccount();
            }

            @Override
            protected void set(Account account) {
                getSavedSearch().setAccount(account);
            }

            @NotNull
            @Override
            public Account getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<Account, String> getAccount() {
        return account;
    }
}
