/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package fr.vendredi.web.selenium.page.more.moretypesdemo;

import fr.vendredi.web.selenium.support.Page;
import fr.vendredi.web.selenium.support.elements.CustomElement;
import fr.vendredi.web.selenium.support.elements.Messages;
import fr.vendredi.web.selenium.support.elements.OrderBy;
import fr.vendredi.web.selenium.support.elements.SearchForm;
import fr.vendredi.web.selenium.support.elements.StringRange;
import fr.vendredi.web.selenium.support.elements.TableAction;

@Page
public class MoreTypesDemoSearch {
    public TableAction table;
    public Messages messages;
    public MoreTypesDemoSearchOrders orders;
    public MoreTypesDemoSearchForm form;

    public static class MoreTypesDemoSearchOrders extends CustomElement {
        public OrderBy numberInt = new OrderBy("moreTypesDemo_numberInt");
        public OrderBy numberLong = new OrderBy("moreTypesDemo_numberLong");
        public OrderBy numberDouble = new OrderBy("moreTypesDemo_numberDouble");
        public OrderBy numberFloat = new OrderBy("moreTypesDemo_numberFloat");
        public OrderBy numberBigInteger = new OrderBy("moreTypesDemo_numberBigInteger");
        public OrderBy numberBigDecimal = new OrderBy("moreTypesDemo_numberBigDecimal");
        public OrderBy dateJavaTemporalDate = new OrderBy("moreTypesDemo_dateJavaTemporalDate");
        public OrderBy dateJavaTemporalTimestamp = new OrderBy("moreTypesDemo_dateJavaTemporalTimestamp");
        public OrderBy dateJoda = new OrderBy("moreTypesDemo_dateJoda");
        public OrderBy dateTimeJoda = new OrderBy("moreTypesDemo_dateTimeJoda");
    }

    public static class MoreTypesDemoSearchForm extends SearchForm {
        public StringRange numberInt = new StringRange("form:numberInt");
        public StringRange numberLong = new StringRange("form:numberLong");
        public StringRange numberDouble = new StringRange("form:numberDouble");
        public StringRange numberFloat = new StringRange("form:numberFloat");
        public StringRange numberBigInteger = new StringRange("form:numberBigInteger");
        public StringRange numberBigDecimal = new StringRange("form:numberBigDecimal");
        public StringRange dateJavaTemporalDate = new StringRange("form:dateJavaTemporalDate");
        public StringRange dateJavaTemporalTimestamp = new StringRange("form:dateJavaTemporalTimestamp");
        public StringRange dateJoda = new StringRange("form:dateJoda");
        public StringRange dateTimeJoda = new StringRange("form:dateTimeJoda");
    }
}