/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package fr.vendredi.web.selenium.page.more.moretypesdemo;

import fr.vendredi.web.selenium.support.Page;
import fr.vendredi.web.selenium.support.elements.CustomElement;
import fr.vendredi.web.selenium.support.elements.DateInput;
import fr.vendredi.web.selenium.support.elements.EditAction;
import fr.vendredi.web.selenium.support.elements.IntegerInput;
import fr.vendredi.web.selenium.support.elements.Messages;

@Page
public class MoreTypesDemoEdit {
    public EditAction action;
    public Messages messages;
    public MoreTypesDemoEditForm form;
    public MoreTypesDemoEditTabs tabs;

    public static class MoreTypesDemoEditForm extends CustomElement {
        public IntegerInput numberInt = new IntegerInput("form:numberInt");
        public IntegerInput numberLong = new IntegerInput("form:numberLong");
        public IntegerInput numberDouble = new IntegerInput("form:numberDouble");
        public IntegerInput numberFloat = new IntegerInput("form:numberFloat");
        public IntegerInput numberBigInteger = new IntegerInput("form:numberBigInteger");
        public IntegerInput numberBigDecimal = new IntegerInput("form:numberBigDecimal");
        public DateInput dateJavaTemporalDate = new DateInput("form:dateJavaTemporalDate");
        public DateInput dateJavaTemporalTimestamp = new DateInput("form:dateJavaTemporalTimestamp");
        public DateInput dateJoda = new DateInput("form:dateJoda");
        public DateInput dateTimeJoda = new DateInput("form:dateTimeJoda");
    };

    public static class MoreTypesDemoEditTabs extends CustomElement {
    };
}