/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/support/element/TableAction.p.vm.java
 */
package fr.vendredi.web.selenium.support.elements;

import static org.openqa.selenium.By.name;

import org.openqa.selenium.By;

public class TableAction extends CustomElement {
    public Paginator paginator;

    public void edit(String value) {
        webClient.clickLinkTitle("Edit " + value);
    }

    public void view(String value) {
        webClient.clickLinkTitle("View " + value);
    }

    public void delete(String value) {
        webClient.clickLinkTitle("Delete " + value);
        confirmDelete();
    }

    
    public void select(String value) {
        webClient.clickLinkTitle("Select " + value);
    }

    public void hasText(String... values) {
        for (String value : values) {
            webClient.hasText(value);
        }
    }

    public void hasSize(int size) {
        paginator.hasSize(size);
    }

    public void editLine(int line) {
        clickLineWithIcon(line, "iconEdit");
    }

    public void selectLine(int line) {
        clickLineWithIcon(line, "iconSelect");
    }

    public void viewLine(int line) {
        clickLineWithIcon(line, "iconView");
    }

    public void deleteLine(int line) {
        clickLineWithIcon(line, "iconDelete");
    }

    public void confirmDelete() {
        webClient.click(name("form:askForDeleteItemDialogYes"));
    }

    private void clickLineWithIcon(int line, String icon) {
        String xpath = "//div[@id='form:searchResults']//table/tbody/tr[" + line + "]/td[@class='actions-column']//div[@class='ui-button ui-icon " + icon
                + "']";
        webClient.click(By.xpath(xpath));
    }
    
    public void selectAll() {
    	String xpath = "//table/thead[@id='form:searchResults_head']/tr/th[@id='form:searchResults:selectAll']/div[contains(@class, 'ui-chkbox-all')]/div[contains(@class, 'ui-chkbox-box')]";
        webClient.waitUntilEnabled(By.xpath(xpath));
        webClient.find(By.xpath(xpath)).click();
        String unselectedCheckbox = "//div[@id='form:searchResults']//td[@class='ui-selection-column']//span[not(contains(@class,'ui-icon-check'))]";
        webClient.waitUntilRemoved(By.xpath(unselectedCheckbox));
    }
    
    public void confirmSelection() {
    	String xpath = "//div[@id='form:searchResults']/div[contains(@class,'ui-datatable-footer')]//div[contains(@class,'iconSelect')]";
        webClient.click(By.xpath(xpath));
    }
}
