/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/support/Autocomplete.p.vm.java
 */
package fr.vendredi.web.selenium.support.element;

import static com.google.common.collect.Lists.newArrayList;
import static com.palominolabs.xpath.XPathUtils.getXPathString;

import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

public class Autocomplete extends CustomElement {
	private final String id;

	public Autocomplete(String id) {
		this.id = id;
	}

	public void autocomplete(String text) {
		webClient.autocomplete(webClient.find(By.id(id + "_input")), text);
	}

	public void autocomplete(String text, String match) {
		webClient.autocomplete(webClient.find(By.id(id + "_input")), text, match);
	}

	public void delete(String value) {
		String xpath = "//div[@id= " + getXPathString(id) + "]//span[@class='ui-autocomplete-token-label' and text()=" + getXPathString(value)
				+ "]/../span[@class='ui-autocomplete-token-icon ui-icon ui-icon-close']";
		webClient.click(By.xpath(xpath));
	}

	public List<String> values() {
		List<String> ret = newArrayList();
		// we test for the number of values, because if there is no values, selenium will wait for the timeout to occurr
		if (getNbValues() >= 1) {
			String spanValues = "//div[@id= " + getXPathString(id) + "]//span[@class='ui-autocomplete-token-label']";
			for (WebElement webElement : webClient.findAll(By.xpath(spanValues))) {
				ret.add(webElement.getText());
			}
		}
		return ret;
	}

	private int getNbValues() {
		String findUlChildren = "//div[@id= " + getXPathString(id) + "]/ul/*";
		int count = webClient.findAll(By.xpath(findUlChildren)).size();
		// -1 so we do not count the input text in which we enter our input
		return count - 1;
	}
}
