/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/support/CustomElement.p.vm.java
 */
package fr.vendredi.web.selenium.support.element;

import fr.vendredi.web.selenium.support.WebClient;

public abstract class CustomElement {
	protected String id;
	protected WebClient webClient;

	public CustomElement() {

	}

	public CustomElement(String id) {
		this.id = id;
	}
}