/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/support/Tab.p.vm.java
 */
package fr.vendredi.web.selenium.support.element;

import static com.palominolabs.xpath.XPathUtils.getXPathString;

import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

import com.google.common.collect.Lists;

public class SaveSearch extends CustomElement {
	public SaveSearch(String id) {
		super(id);
	}

	public void save(String name) {

	}

	public void load(String name) {

	}

	public List<String> values() {
		String xpath = "//span[@id=" + getXPathString(id) + "]/button/span[@class='ui-button-text']";
		webClient.click(By.xpath(xpath));
		String popup = "//div[@id=" + getXPathString(id) + "]/ul/li";
		List<String> ret = Lists.newArrayList();
		for (WebElement webElement : webClient.findAll(By.xpath(popup))) {
			ret.add(webElement.getText());
		}
		return ret;
	}
}
