/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package fr.vendredi.web.selenium.page.address;

import fr.vendredi.web.selenium.support.Page;
import fr.vendredi.web.selenium.support.elements.CustomElement;
import fr.vendredi.web.selenium.support.elements.EditAction;
import fr.vendredi.web.selenium.support.elements.Messages;
import fr.vendredi.web.selenium.support.elements.StringInput;

@Page
public class AddressEdit {
    public EditAction action;
    public Messages messages;
    public AddressEditForm form;
    public AddressEditTabs tabs;

    public static class AddressEditForm extends CustomElement {
        public StringInput streetName = new StringInput("form:streetName");
        public StringInput city = new StringInput("form:city");
    };

    public static class AddressEditTabs extends CustomElement {
    };
}