/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package fr.vendredi.web.selenium.page.role;

import fr.vendredi.web.selenium.support.Page;
import fr.vendredi.web.selenium.support.elements.CustomElement;
import fr.vendredi.web.selenium.support.elements.EditAction;
import fr.vendredi.web.selenium.support.elements.Messages;
import fr.vendredi.web.selenium.support.elements.StringInput;

@Page
public class RoleEdit {
    public EditAction action;
    public Messages messages;
    public RoleEditForm form;
    public RoleEditTabs tabs;

    public static class RoleEditForm extends CustomElement {
        public StringInput roleName = new StringInput("form:roleName");
    };

    public static class RoleEditTabs extends CustomElement {
    };
}