/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package fr.vendredi.web.selenium.page.account;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

import fr.vendredi.domain.Civility;
import fr.vendredi.web.selenium.support.Page;
import fr.vendredi.web.selenium.support.elements.Autocomplete;
import fr.vendredi.web.selenium.support.elements.ChooseEnum;
import fr.vendredi.web.selenium.support.elements.CustomElement;
import fr.vendredi.web.selenium.support.elements.ManyBooleans;
import fr.vendredi.web.selenium.support.elements.Messages;
import fr.vendredi.web.selenium.support.elements.OrderBy;
import fr.vendredi.web.selenium.support.elements.SearchForm;
import fr.vendredi.web.selenium.support.elements.StringRange;
import fr.vendredi.web.selenium.support.elements.TableAction;

@Page
public class AccountSearch {
    public TableAction table;
    public Messages messages;
    public AccountSearchOrders orders;
    public AccountSearchForm form;

    public static class AccountSearchOrders extends CustomElement {
        public OrderBy username = new OrderBy("account_username");
        public OrderBy password = new OrderBy("account_password");
        public OrderBy email = new OrderBy("account_email");
        public OrderBy isEnabled = new OrderBy("account_isEnabled");
        public OrderBy civility = new OrderBy("account_civility");
        public OrderBy firstName = new OrderBy("account_firstName");
        public OrderBy lastName = new OrderBy("account_lastName");
        public OrderBy birthDate = new OrderBy("account_birthDate");
        public OrderBy description = new OrderBy("account_description");
        public OrderBy addressId = new OrderBy("account_addressId");
    }

    public static class AccountSearchForm extends SearchForm {
        public Autocomplete username = new Autocomplete("form:username");
        public Autocomplete password = new Autocomplete("form:password");
        public Autocomplete email = new Autocomplete("form:email");
        public ManyBooleans isEnabled = new ManyBooleans("form:isEnabled");
        public ChooseEnum<Civility> civility = new ChooseEnum<Civility>("form:civility");
        public Autocomplete firstName = new Autocomplete("form:firstName");
        public Autocomplete lastName = new Autocomplete("form:lastName");
        public StringRange birthDate = new StringRange("form:birthDate");
        public Autocomplete description = new Autocomplete("form:description");
        public Autocomplete homeAddress = new Autocomplete("form:homeAddressSelector");
        public Autocomplete coolBooks = new Autocomplete("form:coolBooksSelector");
        public Autocomplete edocs = new Autocomplete("form:edocsSelector");
        public Autocomplete securityRoles = new Autocomplete("form:securityRolesSelector");
    }
}