/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/project/dao/DAOImpl.e.vm.java
 */
package fr.vendredi.dao.more;

import javax.inject.Named;
import javax.inject.Singleton;
import fr.vendredi.dao.more.MoreTypesDemoDao;
import fr.vendredi.dao.support.GenericDao;
import fr.vendredi.domain.more.MoreTypesDemo;

/**
 * JPA 2 Data Access Object for {@link MoreTypesDemo}.
 * Note: do not use @Transactional in the DAO layer.
 */
@Named
@Singleton
public class MoreTypesDemoDao extends GenericDao<MoreTypesDemo, Integer> {
    public MoreTypesDemoDao() {
        super(MoreTypesDemo.class);
    }
}