/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/project/repository/Repository.e.vm.java
 */
package fr.vendredi.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import fr.vendredi.dao.BookDao;
import fr.vendredi.domain.Book;
import fr.vendredi.repository.support.GenericRepository;

/**
 * Note: you may use multiple DAO from this layer.
 */
@Named
@Singleton
public class BookRepository extends GenericRepository<Book, Integer> {

    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected BookRepository() {
        super();
    }

    @Inject
    public BookRepository(BookDao bookDao) {
        super(bookDao);
    }

    @Override
    public Book getNew() {
        return new Book();
    }

    @Override
    public Book getNewWithDefaults() {
        Book result = getNew();
        result.initDefaultValues();
        return result;
    }
}