/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/project/repository/Repository.e.vm.java
 */
package fr.vendredi.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import fr.vendredi.dao.LegacyDao;
import fr.vendredi.domain.Legacy;
import fr.vendredi.domain.LegacyPk;
import fr.vendredi.repository.support.GenericRepository;

/**
 * Note: you may use multiple DAO from this layer.
 */
@Named
@Singleton
public class LegacyRepository extends GenericRepository<Legacy, LegacyPk> {

    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected LegacyRepository() {
        super();
    }

    @Inject
    public LegacyRepository(LegacyDao legacyDao) {
        super(legacyDao);
    }

    @Override
    public Legacy getNew() {
        return new Legacy();
    }

    @Override
    public Legacy getNewWithDefaults() {
        Legacy result = getNew();
        result.initDefaultValues();
        return result;
    }
}