/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/project/dao/DAOImpl.e.vm.java
 */
package fr.vendredi.dao;

import static fr.vendredi.domain.Book_.bookTitle;
import javax.inject.Named;
import javax.inject.Singleton;
import fr.vendredi.dao.BookDao;
import fr.vendredi.dao.support.GenericDao;
import fr.vendredi.domain.Book;

/**
 * JPA 2 Data Access Object for {@link Book}.
 * Note: do not use @Transactional in the DAO layer.
 */
@Named
@Singleton
public class BookDao extends GenericDao<Book, Integer> {
    public BookDao() {
        super(Book.class, bookTitle);
    }
}