/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/project/dao/DAOImpl.e.vm.java
 */
package fr.vendredi.dao;

import javax.inject.Named;
import javax.inject.Singleton;
import fr.vendredi.dao.SavedSearchDao;
import fr.vendredi.dao.support.GenericDao;
import fr.vendredi.domain.SavedSearch;

/**
 * JPA 2 Data Access Object for {@link SavedSearch}.
 * Note: do not use @Transactional in the DAO layer.
 */
@Named
@Singleton
public class SavedSearchDao extends GenericDao<SavedSearch, Integer> {
    public SavedSearchDao() {
        super(SavedSearch.class);
    }
}