/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package fr.vendredi.web.selenium.page.book;

import fr.vendredi.web.selenium.support.Page;
import fr.vendredi.web.selenium.support.elements.CustomElement;
import fr.vendredi.web.selenium.support.elements.EditAction;
import fr.vendredi.web.selenium.support.elements.IntegerInput;
import fr.vendredi.web.selenium.support.elements.ManyToOne;
import fr.vendredi.web.selenium.support.elements.Messages;
import fr.vendredi.web.selenium.support.elements.StringInput;

@Page
public class BookEdit {
    public EditAction action;
    public Messages messages;
    public BookEditForm form;
    public BookEditTabs tabs;

    public static class BookEditForm extends CustomElement {
        public StringInput bookTitle = new StringInput("form:bookTitle");
        public IntegerInput numberOfPages = new IntegerInput("form:numberOfPages");

        public ManyToOne owner = new ManyToOne("form:owner");
    };

    public static class BookEditTabs extends CustomElement {
    };
}