/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/project/printer/Printer.e.vm.java
 */
package fr.vendredi.printer;

import java.util.Locale;
import javax.inject.Named;
import javax.inject.Singleton;
import fr.vendredi.domain.Document;
import fr.vendredi.printer.DiscoverablePrinter;

/**
 * {@link org.springframework.format.Printer} for {@link Document} 
 *
 * @see org.springframework.format.Printer
 * @see DiscoverablePrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class DocumentPrinter extends DiscoverablePrinter<Document> {
    public DocumentPrinter() {
        super(Document.class);
    }

    @Override
    public String print(Document document, Locale locale) {
        if (document == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, document.getDocumentFileName());
        return ret.toString();
    }
}