/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package fr.vendredi.web.selenium.page.savedsearch;

import fr.vendredi.web.selenium.support.Page;
import fr.vendredi.web.selenium.support.elements.Autocomplete;
import fr.vendredi.web.selenium.support.elements.CustomElement;
import fr.vendredi.web.selenium.support.elements.Messages;
import fr.vendredi.web.selenium.support.elements.OrderBy;
import fr.vendredi.web.selenium.support.elements.SearchForm;
import fr.vendredi.web.selenium.support.elements.TableAction;

@Page
public class SavedSearchSearch {
    public TableAction table;
    public Messages messages;
    public SavedSearchSearchOrders orders;
    public SavedSearchSearchForm form;

    public static class SavedSearchSearchOrders extends CustomElement {
        public OrderBy name = new OrderBy("savedSearch_name");
        public OrderBy formClassname = new OrderBy("savedSearch_formClassname");
        public OrderBy formContent = new OrderBy("savedSearch_formContent");
        public OrderBy accountId = new OrderBy("savedSearch_accountId");
    }

    public static class SavedSearchSearchForm extends SearchForm {
        public Autocomplete name = new Autocomplete("form:name");
        public Autocomplete formClassname = new Autocomplete("form:formClassname");
        public Autocomplete account = new Autocomplete("form:accountSelector");
    }
}