/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/SearchFormsIT.p.vm.java
 */
package fr.vendredi.web.selenium;

import static org.fest.assertions.Assertions.assertThat;

import java.util.concurrent.TimeUnit;

import org.fest.assertions.Assertions;
import org.junit.Test;

import fr.vendredi.web.selenium.page.account.AccountEdit;
import fr.vendredi.web.selenium.page.account.AccountSearch;
import fr.vendredi.web.selenium.page.role.RoleSearch;
import fr.vendredi.web.selenium.support.SeleniumTest;

public class IronManIT extends SeleniumTest {
	AccountSearch accountSearch;
	AccountEdit accountEdit;
	RoleSearch roleSearch;

	@Test
	public void ironMan() throws InterruptedException {
		englishHomePage();
		loginAsAnAdmin();
		loggedHomePage.accounts();
		webClient.message("toto");
		accountSearch.form.username.complete("dem", "demo");
		accountSearch.form.username.type("admin");
		accountSearch.form.isEnabled.choose(true);
		accountSearch.form.search();
		accountSearch.table.hasSize(2);
//		accountSearch.orders.username.up();
//		accountSearch.table.hasSize(2);
		accountSearch.table.editLine(1);
//		accountEdit.form.username.type("iron man");
//		accountEdit.form.homeAddress.complete("tokio", "Tokyo");
		accountEdit.tabs.securityRoles.open();
//		accountEdit.tabs.securityRoles.remove("ROLE_ADMIN");
//		accountEdit.tabs.securityRoles.confirmRemove();
//		accountEdit.tabs.securityRoles.remove("ROLE_MONITORING");
//		accountEdit.tabs.securityRoles.confirmRemove();
//		accountEdit.tabs.securityRoles.remove("ROLE_USER");
//		accountEdit.tabs.securityRoles.confirmRemove();
		System.out.println("Tab openend");
		TimeUnit.SECONDS.sleep(2);
		assertThat(accountEdit.tabs.securityRoles.values("roleName")).hasSize(3).contains("ROLE_ADMIN");
		assertThat(accountEdit.tabs.securityRoles.value("roleName", 2)).isEqualTo("ROLE_USER");
		accountEdit.tabs.securityRoles.search();
		roleSearch.table.selectAll();
		roleSearch.table.confirmSelection();
		accountEdit.tabs.securityRoles.add();
		TimeUnit.SECONDS.sleep(10);
	}
}
