/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/converter/JsfConverter.e.vm.java
 */
package fr.vendredi.web.converter.more;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import fr.vendredi.domain.more.MoreTypesDemo;
import fr.vendredi.repository.more.MoreTypesDemoRepository;
import fr.vendredi.web.converter.GenericJsfConverter;

/**
 * JSF converter for {@link MoreTypesDemo}.
 * @see GenericJsfConverter
 */
@Named
@Singleton
public class MoreTypesDemoJsfConverter extends GenericJsfConverter<MoreTypesDemo, Integer> {
    @Inject
    public MoreTypesDemoJsfConverter(MoreTypesDemoRepository moreTypesDemoRepository) {
        super(moreTypesDemoRepository, MoreTypesDemo.class, Integer.class);
    }
}